# Generated by Django 3.2.25 on 2025-03-14 17:34

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('leveladvisor', 'LevelAdvisor')], max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('courseCode', models.CharField(blank=True, max_length=15, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('C', 'C'), ('E', 'E'), ('R', 'R')], default='C', max_length=40, null=True)),
                ('category', models.CharField(blank=True, choices=[('nursing course', 'NC'), ('life science', 'LS'), ('non nursing course', 'NNC')], default='NNC', max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.college')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=9)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instructor_remark', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=50, null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('semester', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.semester')),
                ('session', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.session')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.session')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.level'),
        ),
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='courses', to='app.Programme'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.semester'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.customuser')),
                ('otherNames', models.CharField(blank=True, max_length=80, null=True)),
                ('surname', models.CharField(blank=True, max_length=80, null=True)),
                ('currentLevel', models.CharField(blank=True, max_length=80, null=True)),
                ('matricNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('jambNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=15, null=True)),
                ('studentPhoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('currentSession', models.CharField(blank=True, max_length=20, null=True)),
                ('primaryEmail', models.CharField(blank=True, max_length=120, null=True)),
                ('studentEmail', models.CharField(blank=True, max_length=120, null=True)),
                ('bloodGroup', models.CharField(blank=True, max_length=20, null=True)),
                ('genoType', models.CharField(blank=True, max_length=20, null=True)),
                ('modeOfEntry', models.CharField(blank=True, max_length=50, null=True)),
                ('entryLevel', models.CharField(blank=True, max_length=50, null=True)),
                ('degree', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=110, null=True)),
                ('stateOfOrigin', models.CharField(blank=True, max_length=110, null=True)),
                ('localGovtArea', models.CharField(blank=True, max_length=110, null=True)),
                ('passport', models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='images/')),
                ('student_status', models.CharField(blank=True, choices=[('inprogress', 'inprogress'), ('failed', 'failed'), ('graduated', 'graduated')], default='inprogress', max_length=100, null=True)),
                ('student_stream', models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b')], default='b', max_length=100, null=True)),
                ('college', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.college')),
                ('department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('entrySession', models.ManyToManyField(default=None, null=True, related_name='entrySession', through='app.Enrollment', to='app.Session')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grade_type', models.CharField(blank=True, max_length=5, null=True)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('total_point', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('grade_remark', models.CharField(choices=[('passed', 'passed'), ('failed', 'failed'), ('pending', 'pending')], default='pending', max_length=20)),
                ('passed', models.BooleanField(default=False)),
                ('carried_over', models.BooleanField(default=False)),
                ('result_date', models.DateField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='app.registration')),
            ],
            options={
                'unique_together': {('registration', 'attempt_number')},
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
        migrations.CreateModel(
            name='LevelAdvisor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.customuser')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.level')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.customuser')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('departmental_email', models.CharField(blank=True, max_length=90, null=True)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
        migrations.CreateModel(
            name='confirmRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('totalUnits', models.CharField(blank=True, max_length=100, null=True)),
                ('gpa', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.level')),
                ('semester', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.semester')),
                ('session', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.session')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
