# Generated by Django 3.2.25 on 2025-03-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='entrySession',
        ),
        migrations.AddField(
            model_name='student',
            name='entrySession',
            field=models.ManyToManyField(default=None, null=True, related_name='entrySession', through='app.Enrollment', to='app.Session'),
        ),
    ]
