# Generated by Django 3.2.25 on 2025-03-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_stream',
            field=models.CharField(blank=True, default='b', max_length=100, null=True),
        ),
    ]
