# Generated by Django 3.2.25 on 2025-03-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='department',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='passport',
            field=models.ImageField(blank=True, default='images/placeholder.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='leveladvisor',
            name='passport',
            field=models.ImageField(blank=True, default='images/placeholder.png', null=True, upload_to='images/'),
        ),
    ]
