# Generated by Django 3.2.25 on 2025-03-15 04:33

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20250314_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.ImageField(blank=True, default='images/placeholder.png', null=True, upload_to=app.models.student_passport_upload),
        ),
    ]
