# Generated by Django 3.2.25 on 2025-03-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20250316_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='entrySession',
        ),
        migrations.AddField(
            model_name='student',
            name='entrySession',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
