# Generated by Django 3.2.25 on 2024-12-04 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='programmes',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='department',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app.programme'),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_with_previous_programme', to='app.programme'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='name',
            field=models.CharField(blank=True, choices=[('ond', 'OND Nursing'), ('hnd', 'HND Nursing')], max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.programme'),
        ),
    ]
