# Generated by Django 3.2.25 on 2025-01-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20250101_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='instructor_remark',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20, null=True),
        ),
    ]
