# Generated by Django 3.2.25 on 2025-01-15 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_registration_instructor_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('leveladvisor', 'LevelAdvisor')], max_length=15),
        ),
        migrations.CreateModel(
            name='LevelAdvisor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.customuser')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.level')),
            ],
        ),
    ]
