# Generated by Django 3.2.25 on 2025-01-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20250115_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='previous_programme',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('nursing course', 'NC'), ('life science', 'LS'), ('non nursing course', 'NNC')], default='NNC', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.CharField(blank=True, choices=[('inprogress', 'inprogress'), ('failed', 'failed'), ('graduated', 'graduated')], default='inprogress', max_length=100, null=True),
        ),
    ]
