# Generated by Django 3.2.25 on 2025-01-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20250116_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('E', 'E'), ('R', 'R')], default='C', max_length=40, null=True),
        ),
    ]
