# Generated by Django 3.2.25 on 2025-02-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='programme',
        ),
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='courses', to='app.Programme'),
        ),
    ]
