# Generated by Django 3.2.25 on 2025-02-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20250204_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
