# Generated by Django 3.2.25 on 2025-02-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_programme_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
